var states = {
    ENTRY: "",
    NEW_GAME: "NEW_GAME",
    CHOOSE_STARTER: "CHOOSE_STARTER",
    CONTINUE_GAME: "CONTINUE_GAME",
    RENEW_GAME: "RENEW_GAME",
    CONFIRM_RENEW_GAME: "CONFIRM_RENEW_GAME",
    TUTORIAL: "TUTORIAL",
    TUTORIAL_BATTLE: "TUTORIAL_BATTLE",
    WILD_BATTLE: "WILD_BATTLE",
    CHALLENGE_BATTLE: "CHALLENGE_BATTLE"
};

module.exports = states;